### ISSUE TITLE
Feature Request: Network graph

### ISSUE THREAD

**Issue by Olivered** [demonsaw/demonsaw#38]
Add an optional central pane to demonsaw that gives a visual of the network from the client's perspective. This may be helpful in debugging private networks in the future

**Comment by ghost** [comment]
What kind of information are you wanting to be graphed? The router list tab already shows a list of all data routers that the message router has enabled, your client shows the online status (the color circle next to router, the color is the status code) and version number of the router.

If you are wanting more in-depth information like ping latency, bandwidth, and details relating to any transfers you've pushed through them; Demonsaw attempts to do as much as possible without having to write data to disk, meaning it is already doing and storing a lot in memory and adding stat tracking for X amount of routers for X amount of clients enabled is a lot of overhead.

Personal thoughts on this, I think that would be cool to look at but not very useful since the network is very linear, it doesn't add any real information for debugging, and it is essentially just more feature bloat considering this is a privacy focused application.
