### ISSUE TITLE
Feature request.

### ISSUE THREAD

**Issue by hacker4765** [demonsaw/demonsaw#39]
The have been many instances of time correlative attack being used to either identify or help identify "anonymous" clients on many platforms. There have been innovations on how to circumvent such techniques like from the i2p-bote addon. Could some form of time delayed upload/ time delayed download be established With either junk or real encrypted packets being transmitted/received  until the real data is uploaded/downloaded. If this is planned/ added as an option for extra security the clients using this could temporarily become a message router until the semi variable and semi random delay is up. 

Though a combination of a delay and data routers randomly sending files at low point in network traffic, there is no time correlation possible and overall network stability and overall bandwidth consistency throughout the day.

**Comment by hacker4765** [comment]
Just to clarify for data and message sending there could be variable delays both on client and on the routers, The options should  only be defined from the client to keep everything compatible and faster for the net setups that might not need this extra layer on top of everything else already implemented. Great software so far though.

**Comment by hacker4765** [comment]
Just to clarify it a little more, I intended it as a delayed download by a client or delaying when a file is available for download.

**Comment by ghost** [comment]
Are you proposing this change to prevent de-anonymization from a data router? As in someone has is running a data router used by the main message router and wants to find the IP of a user, initiates a download from them and then prays to FSM that the transfer goes through their router?

One benefit of being on a larger network like the public one is that there are a lot of data routers and that you can select the ones you want to use/trust in the transfer router tab. Demonsaw assigns random data routers for each client requested transfer, file transfers are sharded (transfer spread across multiple data routers so that no one router transfers the entire file), and multiple clients can be sharing the same file and contributing to the transfer (swarm). So if you were attempting to do a client de-anonymization attack from a data router, after tricking the message router admin to use your router, then you'd still have to be extremely lucky to get just the target or expand your attack to everyone who responded to the file request.

There is already a delay of sorts added into Demonsaw, but it's goal is to prevent entropy drain attacks.

Also. Clients 'becoming' a router is a terrible idea, that immediately violates the privacy of Demonsaw. The routers are between clients for a reason, to prevent clients from communicating directly with clients.

I2P-Bote is an email add-on for an already anonymous network implementation, it's an alternative solution for regular email servers. It's a completely different solution for a completely different problem.
